Repository brain-tec/bank-statement-reconcile, pull requests merged in 2019-04, with the labels that each got.

#151 Syncing from upstream OCA/account-reconcile (11.0)
  account_mass_reconcile_ref_deep_search/static/description/icon.png
  account_mass_reconcile_transaction_ref/static/description/icon.png
  base_transaction_id/__manifest__.py
  base_transaction_id/static/description/icon.png
  base_transaction_id/static/src/js/account_widgets.js
  base_transaction_id/static/src/xml/account_reconciliation.xml
  base_transaction_id/views/base_transaction_id.xml
Labels: 11.0

#152 Syncing from upstream OCA/account-reconcile (12.0)
  base_transaction_id/static/description/icon.png
  base_transaction_id/static/src/xml/account_reconciliation.xml
Labels: 12.0

#153 Syncing from upstream OCA/account-reconcile (8.0)
  account_advanced_reconcile/static/description/icon.png
  account_easy_reconcile/static/description/icon.png
  account_invoice_reference/static/description/icon.png
  account_statement_operation_multicompany/static/description/icon.png
  account_statement_operation_rule/static/description/icon.png
  account_statement_operation_rule_dunning_fees/static/description/icon.png
  base_transaction_id/static/description/icon.png
Labels: 8.0

#154 Syncing from upstream OCA/account-reconcile (9.0)
  account_mass_reconcile_ref_deep_search/static/description/icon.png
  account_mass_reconcile_transaction_ref/static/description/icon.png
  account_move_bankaccount_import/static/description/icon.png
  account_move_base_import/static/description/icon.png
  account_move_so_import/static/description/icon.png
  account_move_transactionid_import/static/description/icon.png
  account_operation_rule/static/description/icon.png
  base_transaction_id/static/description/icon.png
Labels: 9.0

#155 Syncing from upstream OCA/account-reconcile (10.0)
  account_mass_reconcile_ref_deep_search/static/description/icon.png
  account_mass_reconcile_transaction_ref/static/description/icon.png
  account_move_base_import/static/description/icon.png
  base_transaction_id/static/description/icon.png
Labels: 10.0

#156 [bt#4855] Der Button AUTOMATISCHE ABSTIMMUNG: da passiert nix
  base_transaction_id/models/account_bank_statement_line.py
Labels: 11.0.project_la_443, enhancement

#157 [bt#4855] Der Button AUTOMATISCHE ABSTIMMUNG: da passiert nix
  base_transaction_id/models/account_bank_statement_line.py
Labels: 11.0.project_la_443

#158 Syncing from upstream OCA/account-reconcile (12.0)
  account_partner_reconcile/README.rst
  account_partner_reconcile/__init__.py
  account_partner_reconcile/__manifest__.py
  account_partner_reconcile/i18n/account_partner_reconcile.pot
  account_partner_reconcile/models/__init__.py
  account_partner_reconcile/models/res_partner.py
  account_partner_reconcile/readme/CONFIGURE.rst
  account_partner_reconcile/readme/CONTRIBUTORS.rst
  account_partner_reconcile/readme/DESCRIPTION.rst
  account_partner_reconcile/readme/USAGE.rst
  account_partner_reconcile/static/description/icon.png
  account_partner_reconcile/static/description/index.html
  account_partner_reconcile/tests/__init__.py
  account_partner_reconcile/tests/test_account_partner_reconcile.py
  account_partner_reconcile/views/res_partner_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_partner_reconcile/odoo/addons/account_partner_reconcile
  setup/account_partner_reconcile/setup.py
Labels: 12.0
